// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Article is the golang structure of table article for DAO operations like Where/Data.
type Article struct {
	g.Meta     `orm:"table:article, do:true"`
	ArticleId  interface{} //
	Title      interface{} // 标题
	Content    interface{} // 内容
	Sort       interface{} // 排序
	IsDelete   interface{} // 删除 0-否 1-是
	CreateTime interface{} // 创建时间
	UpdateTime interface{} // 更新时间
	UpdateAt   *gtime.Time // 变更时间
}
