// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// CategoryRelation is the golang structure of table category_relation for DAO operations like Where/Data.
type CategoryRelation struct {
	g.Meta     `orm:"table:category_relation, do:true"`
	Id         interface{} //
	CategoryId interface{} // 分类ID
	Type       interface{} // 类型 1-文章
	RelateId   interface{} // 关联ID
	IsDelete   interface{} // 删除 0-否 1-是
	CreateTime interface{} // 创建时间
	UpdateTime interface{} // 更新时间
	UpdateAt   *gtime.Time // 变更时间
}
