// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Tag is the golang structure of table tag for DAO operations like Where/Data.
type Tag struct {
	g.Meta     `orm:"table:tag, do:true"`
	TagId      interface{} //
	TagName    interface{} // 标签名称
	IsDelete   interface{} // 删除 0-否 1-是
	CreateTime interface{} // 创建时间
	UpdateTime interface{} // 更新时间
	UpdateAt   *gtime.Time // 变更时间
}
