// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta     `orm:"table:user, do:true"`
	UserId     interface{} //
	Account    interface{} // 账号
	Password   interface{} // 密码
	Salt       interface{} // salt
	UserName   interface{} // 用户名
	Gender     interface{} // 性别 0-隐藏 1-男 2-女
	Mobile     interface{} // 手机号
	CreateTime interface{} // 创建时间
	UpdateTime interface{} // 更新时间
	UpdateAt   *gtime.Time // 变更时间
}
