
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name: "myblog"
    arch: "amd64"
    system: "linux" # 在Linux服务上跑
  gen:
    dao:
      - link: "mysql:root:123456@tcp(192.168.10.33:3306)/myblog"
        descriptionTag: true
        noModelComment: true