// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myblog-gf/internal/dao/internal"
)

// internalTagRelationDao is internal type for wrapping internal DAO implements.
type internalTagRelationDao = *internal.TagRelationDao

// tagRelationDao is the data access object for table tag_relation.
// You can define custom methods on it to extend its functionality as you wish.
type tagRelationDao struct {
	internalTagRelationDao
}

var (
	// TagRelation is globally public accessible object for table tag_relation operations.
	TagRelation = tagRelationDao{
		internal.NewTagRelationDao(),
	}
)

// Fill with you ideas below.
