// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Article is the golang structure for table article.
type Article struct {
	ArticleId  int         `json:"articleId"  description:""`
	Title      string      `json:"title"      description:"标题"`
	Content    string      `json:"content"    description:"内容"`
	Sort       uint        `json:"sort"       description:"排序"`
	IsDelete   uint        `json:"isDelete"   description:"删除 0-否 1-是"`
	CreateTime uint        `json:"createTime" description:"创建时间"`
	UpdateTime uint        `json:"updateTime" description:"更新时间"`
	UpdateAt   *gtime.Time `json:"updateAt"   description:"变更时间"`
}
