// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Category is the golang structure for table category.
type Category struct {
	CategoryId   int         `json:"categoryId"   description:""`
	CategoryType uint        `json:"categoryType" description:"分类类型"`
	CategoryName string      `json:"categoryName" description:"分类名称"`
	ParentId     uint        `json:"parentId"     description:"上级ID"`
	IsDelete     uint        `json:"isDelete"     description:"删除 0-否 1-是"`
	CreateTime   uint        `json:"createTime"   description:"创建时间"`
	UpdateTime   uint        `json:"updateTime"   description:"更新时间"`
	UpdateAt     *gtime.Time `json:"updateAt"     description:"变更时间"`
}
