// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	UserId     int         `json:"userId"     description:""`
	Account    string      `json:"account"    description:"账号"`
	Password   string      `json:"password"   description:"密码"`
	Salt       string      `json:"salt"       description:"salt"`
	UserName   string      `json:"userName"   description:"用户名"`
	Gender     uint        `json:"gender"     description:"性别 0-隐藏 1-男 2-女"`
	Mobile     string      `json:"mobile"     description:"手机号"`
	CreateTime uint        `json:"createTime" description:"创建时间"`
	UpdateTime uint        `json:"updateTime" description:"更新时间"`
	UpdateAt   *gtime.Time `json:"updateAt"   description:"变更时间"`
}
